name: Build & Publish Latest

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: github.repository_owner == 'leduong'
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        ref: production

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: leduong
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set environment variables
      run: echo RELEASE=$(jq -r .release.version ./src/package.json) >> $GITHUB_ENV

    - name: Build & Publish Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        tags: leduong/wg-easy:latest, leduong/wg-easy:${{ env.RELEASE }}
